// <auto-generated />
using System;
using APIStuff.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIStuff.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210426053554_APIStuff")]
    partial class APIStuff
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIStuff.Models.ActionHeroes", b =>
                {
                    b.Property<int>("ActionHeroesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("epicMovies")
                        .HasColumnType("int");

                    b.Property<string>("heroName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActionHeroesID");

                    b.ToTable("ActionHeroes");
                });

            modelBuilder.Entity("APIStuff.Models.Samurai", b =>
                {
                    b.Property<int>("samuraiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("battlesFought")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("samuraiID");

                    b.ToTable("Samurai");
                });
#pragma warning restore 612, 618
        }
    }
}
